[build]
  command = "npm install && npm run build"
  publish = "public"
  functions = "functions"

[dev]
  command = "npm run dev"
  port = 3001
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
